include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "openapi/**"
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
