name: riverpod_structure
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  change_case: ^2.0.1
  collection: ^1.18.0
  dartx: ^1.2.0
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_flavor: ^3.1.3
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  stack_trace: ^1.11.1
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0
  universal_html: ^2.2.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets
      package_parameter_enabled: false
    enabled: true
  fonts:
    outputs:
      class_name: AppFonts
    enabled: true
  line_length: 80

flutter:
  assets:
    - assets/google_fonts/
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
  uses-material-design: true
